### ISSUE TITLE
Proposition following exactly RegExp.prototype.exec

### ISSUE THREAD

**Issue by caub** [tc39/String.prototype.matchAll#12]
This proposal is great

I think .matchAll could just put the results of RegExp.prototype.exec in an array (or iterator):

```
function* exec(re, s){
	let x;
	while(x=re.exec(s)){
		yield x;
	}
}
//or
function* exec(re, s){
	const x = re.exec(s);
	if (!x) return;
 	yield x;
	yield* exec(re, s);
}
// test case
for (let m of exec(/x([aeiouy]+)/gi, 'hxeoolxo')) console.log(m)
```
then maybe `String.prototype.matchAll = function(re){return [...exec(re, this)]}`

Also why not overwriting the existing `String.prototype.match` with this, to have it returning an array of arrays when the global flag is set? backward compatibility?

**Comment by ljharb** [comment]
Certainly backwards compatibility is critical, so it must be a new method.

What you are describing with exec is effectively what this proposal does already - just using spec language instead of JavaScript.
